# List of directories/files to ignore

IgnorePath "/logs/*" # No logs needed
IgnorePath "/mnt/*" # All important data to backup is in other dirs
IgnorePath "/nix/*" # Nix data, will be regenerated anyway
IgnorePath "/timeshift/*" # Timeshift data, should be dealt with elsewhere
    IgnorePath "/run/timeshift/*"
IgnorePath "/var/*" # All /var data, lot of big files here that can be regenerated
IgnorePath "/usr/*" # Stuff that gets regenerated/added, when packages get installed

# /boot
IgnorePath "/boot/*.img" # Ignore big image files in boot, also EFI-related files
    IgnorePath "/boot/vmlinuz-linux"
    IgnorePath "/boot/vmlinuz-linux-*"
    IgnorePath "/boot/EFI/BOOT/bootx64.efi"
    IgnorePath "/boot/EFI/BOOT/BOOT.CSV"
IgnorePath /boot/EFI/BOOT/themes/refind-theme-regular/.devcontainer/devcontainer.json # Unnecessary theme files
    IgnorePath /boot/EFI/BOOT/themes/refind-theme-regular/.gitignore
    IgnorePath /boot/EFI/BOOT/themes/refind-theme-regular/LICENSE
    IgnorePath /boot/EFI/BOOT/themes/refind-theme-regular/README.md
    IgnorePath "/boot/EFI/BOOT/icons/*"
    IgnorePath "/boot/EFI/BOOT/icons-backup"

# /etc directories, either for privacy or as they will be regenerated on install
IgnorePath "/etc/.updated" # Auto-generated
IgnorePath "/etc/ca-certificates/*" # Certificate data, not needed
    IgnorePath "/etc/ssl/certs/*" # Avoid ghost directories
IgnorePath "/etc/cups/ppd/*" # Should be added when drivers get installed
IgnorePath "/etc/cron.d/timeshift-hourly" # Automatically generated by timeshift
IgnorePath "/etc/dconf/db/*" # DBs are not something that make sense to sync
IgnorePath "/etc/ld.so.cache" # No need for cache
IgnorePath "/etc/libvirt/*" # Gets regenerated anyway, and needs to be manually dealt with
IgnorePath "/etc/NetworkManager/system-connections/*" # Hahaha, nice try
IgnorePath "/etc/nvme/*" # Not dealing with NVME over Fabrics
IgnorePath "/etc/openrgb/OpenRGB.json" # OpenRGB writes this automatically
    IgnorePath "/OpenRGB.json"
IgnorePath "/etc/pacman.d/gnupg/*" # Pacman deals with keyring automatically
IgnorePath "/etc/pacman.d/mirrorlist" # Reflector deals with mirrors automatically 
    IgnorePath "/etc/pacman.d/mirrorlist.pacnew"
IgnorePath "/etc/printcap" # Automatically generated with CUPS
IgnorePath "/etc/resolv.conf" # Auto-generated by Tailscale
    IgnorePath "/etc/resolv.*.conf"
IgnorePath "/etc/systemd/system/*.target.wants" # Avoid a bunch of ghost directories
    IgnorePath "/etc/systemd/user/*.target.wants"
IgnorePath "/etc/ssh/*_key" # Avoid giving out SSH keys to public
    IgnorePath "/etc/ssh/*_key.pub"
IgnorePath "/etc/wireguard/*" # Avoid giving out Wireguard keys to public
IgnorePath "/etc/X11/*" # Anything X11
IgnorePath "/etc/xml/*" # XML catalog