# Bootloader theme files
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/nimbus-mono-14.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/nimbus-mono-16.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/nimbus-mono-18.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/nimbus-mono-28.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/nimbus-mono-30.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/nimbus-mono-32.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/nimbus-mono-42.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/nimbus-mono-44.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/nimbus-mono-46.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/source-code-pro-extralight-14.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/source-code-pro-extralight-16.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/source-code-pro-extralight-18.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/source-code-pro-extralight-28.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/source-code-pro-extralight-30.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/source-code-pro-extralight-32.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/source-code-pro-extralight-42.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/source-code-pro-extralight-44.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/source-code-pro-extralight-46.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/ubuntu-mono-14.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/ubuntu-mono-16.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/ubuntu-mono-18.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/ubuntu-mono-28.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/ubuntu-mono-30.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/ubuntu-mono-32.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/ubuntu-mono-42.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/ubuntu-mono-44.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/fonts/ubuntu-mono-46.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/arrow_left.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/arrow_right.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/bg.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/bg_dark.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/func_about.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/func_bootorder.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/func_csr_rotate.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/func_exit.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/func_firmware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/func_hidden.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/func_reset.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/func_shutdown.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_alpine.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_altlinux.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_android.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_antergos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_apricity.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_arch.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_artix.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_astos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_bedrock.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_blackarch.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_cachyos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_cent.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_chakra.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_chrome.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_clover.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_core.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_crunchbang.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_debian.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_deepin.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_elementary.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_endeavouros.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_fatdog.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_fedora.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_freebsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_frugalware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_gentoo.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_ghostbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_goofiboot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_gummiboot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_haiku.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_hwtest.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_kali.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_kubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_legacy.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_linux.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_linuxmint.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_lubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_macos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_mageia.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_mandriva.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_manjaro.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_mx.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_neon.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_netbootxyz.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_netbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_network.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_nixos-alt.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_nixos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_nobara.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_oc.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_openbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_opencore.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_openmandriva.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_opensuse.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_parabola.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_parrot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_pcbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_pclinuxos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_phoenixos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_pop.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_proxmox.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_puppy.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_redhat.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_refind.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_refit.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_remixos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_rosa.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_sabayon.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_slackware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_solus.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_steam.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_suse.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_systemd-boot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_systemd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_tails.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_ubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_ubuntubudgie.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_ubuntudde.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_ubuntugnome.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_ubuntugnome_alt.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_ubuntumate.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_ubuntustudio.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_unknown.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_vmware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_void.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_win.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_win8-alt1.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_win8-alt2.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_win8.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_windows-alt.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_windows.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_xubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/os_zorin.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/selection-big.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/selection-small.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/selection_dark-big.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/selection_dark-small.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/tool_apple_rescue.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/tool_fwupdate.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/tool_memtest.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/tool_mok_tool.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/tool_netboot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/tool_part.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/tool_rescue.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/tool_shell.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/tool_windows_rescue.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/vol_external.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/vol_internal.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/vol_net.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/128-48/vol_optical.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/arrow_left.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/arrow_right.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/bg.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/bg_dark.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/func_about.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/func_bootorder.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/func_csr_rotate.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/func_exit.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/func_firmware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/func_hidden.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/func_reset.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/func_shutdown.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_alpine.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_altlinux.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_android.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_antergos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_apricity.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_arch.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_artix.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_astos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_bedrock.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_blackarch.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_cachyos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_cent.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_chakra.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_chrome.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_clover.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_core.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_crunchbang.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_debian.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_deepin.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_elementary.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_endeavouros.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_fatdog.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_fedora.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_freebsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_frugalware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_gentoo.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_ghostbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_goofiboot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_gummiboot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_haiku.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_hwtest.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_kali.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_kubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_legacy.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_linux.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_linuxmint.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_lubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_macos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_mageia.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_mandriva.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_manjaro.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_mx.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_neon.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_netbootxyz.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_netbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_network.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_nixos-alt.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_nixos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_nobara.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_oc.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_openbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_opencore.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_openmandriva.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_opensuse.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_parabola.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_parrot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_pcbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_pclinuxos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_phoenixos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_pop.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_proxmox.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_puppy.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_redhat.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_refind.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_refit.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_remixos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_rosa.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_sabayon.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_slackware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_solus.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_steam.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_suse.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_systemd-boot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_systemd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_tails.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_ubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_ubuntubudgie.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_ubuntudde.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_ubuntugnome.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_ubuntugnome_alt.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_ubuntumate.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_ubuntustudio.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_unknown.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_vmware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_void.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_win.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_win8-alt1.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_win8-alt2.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_win8.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_windows-alt.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_windows.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_xubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/os_zorin.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/selection-big.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/selection-small.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/selection_dark-big.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/selection_dark-small.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/tool_apple_rescue.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/tool_fwupdate.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/tool_memtest.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/tool_mok_tool.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/tool_netboot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/tool_part.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/tool_rescue.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/tool_shell.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/tool_windows_rescue.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/vol_external.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/vol_internal.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/vol_net.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/256-96/vol_optical.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/arrow_left.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/arrow_right.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/bg.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/bg_dark.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/func_about.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/func_bootorder.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/func_csr_rotate.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/func_exit.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/func_firmware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/func_hidden.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/func_reset.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/func_shutdown.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_alpine.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_altlinux.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_android.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_antergos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_apricity.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_arch.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_artix.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_astos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_bedrock.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_blackarch.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_cachyos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_cent.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_chakra.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_chrome.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_clover.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_core.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_crunchbang.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_debian.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_deepin.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_elementary.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_endeavouros.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_fatdog.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_fedora.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_freebsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_frugalware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_gentoo.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_ghostbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_goofiboot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_gummiboot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_haiku.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_hwtest.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_kali.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_kubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_legacy.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_linux.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_linuxmint.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_lubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_macos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_mageia.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_mandriva.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_manjaro.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_mx.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_neon.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_netbootxyz.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_netbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_network.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_nixos-alt.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_nixos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_nobara.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_oc.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_openbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_opencore.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_openmandriva.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_opensuse.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_parabola.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_parrot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_pcbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_pclinuxos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_phoenixos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_pop.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_proxmox.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_puppy.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_redhat.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_refind.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_refit.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_remixos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_rosa.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_sabayon.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_slackware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_solus.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_steam.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_suse.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_systemd-boot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_systemd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_tails.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_ubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_ubuntubudgie.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_ubuntudde.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_ubuntugnome.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_ubuntugnome_alt.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_ubuntumate.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_ubuntustudio.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_unknown.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_vmware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_void.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_win.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_win8-alt1.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_win8-alt2.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_win8.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_windows-alt.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_windows.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_xubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/os_zorin.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/selection-big.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/selection-small.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/selection_dark-big.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/selection_dark-small.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/tool_apple_rescue.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/tool_fwupdate.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/tool_memtest.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/tool_mok_tool.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/tool_netboot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/tool_part.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/tool_rescue.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/tool_shell.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/tool_windows_rescue.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/vol_external.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/vol_internal.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/vol_net.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/384-144/vol_optical.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/arrow_left.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/arrow_right.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/bg.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/bg_dark.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/func_about.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/func_bootorder.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/func_csr_rotate.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/func_exit.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/func_firmware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/func_hidden.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/func_reset.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/func_shutdown.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_alpine.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_altlinux.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_android.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_antergos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_apricity.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_arch.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_artix.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_astos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_bedrock.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_blackarch.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_cachyos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_cent.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_chakra.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_chrome.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_clover.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_core.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_crunchbang.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_debian.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_deepin.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_elementary.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_endeavouros.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_fatdog.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_fedora.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_freebsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_frugalware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_gentoo.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_ghostbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_goofiboot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_gummiboot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_haiku.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_hwtest.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_kali.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_kubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_legacy.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_linux.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_linuxmint.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_lubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_macos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_mageia.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_mandriva.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_manjaro.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_mx.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_neon.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_netbootxyz.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_netbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_network.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_nixos-alt.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_nixos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_nobara.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_oc.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_openbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_opencore.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_openmandriva.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_opensuse.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_parabola.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_parrot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_pcbsd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_pclinuxos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_phoenixos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_pop.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_proxmox.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_puppy.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_redhat.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_refind.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_refit.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_remixos.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_rosa.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_sabayon.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_slackware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_solus.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_steam.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_suse.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_systemd-boot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_systemd.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_tails.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_ubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_ubuntubudgie.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_ubuntudde.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_ubuntugnome.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_ubuntugnome_alt.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_ubuntumate.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_ubuntustudio.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_unknown.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_vmware.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_void.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_win.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_win8-alt1.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_win8-alt2.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_win8.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_windows-alt.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_windows.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_xubuntu.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/os_zorin.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/selection-big.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/selection-small.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/selection_dark-big.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/selection_dark-small.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/tool_apple_rescue.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/tool_fwupdate.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/tool_memtest.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/tool_mok_tool.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/tool_netboot.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/tool_part.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/tool_rescue.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/tool_shell.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/tool_windows_rescue.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/vol_external.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/vol_internal.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/vol_net.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/icons/512-192/vol_optical.png 755
CopyFile /boot/EFI/BOOT/themes/refind-theme-regular/theme.conf 755
CopyFile /boot/EFI/BOOT/refind.conf.bak 755